Traceback (most recent call last):
  File "C:\Users\cross\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cross\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\cross\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\cross\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\cross\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\cross\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\dev\python-email\src\web\admin_routes.py", line 42, in admin_index
    return render_template('admin_dashboard.html', evidences=evidences, page=page, total_pages=total_pages, admin_csrf=session['admin_csrf'])
  File "C:\Users\cross\AppData\Roaming\Python\Python313\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\cross\AppData\Roaming\Python\Python313\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\cross\AppData\Roaming\Python\Python313\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\cross\AppData\Roaming\Python\Python313\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\dev\python-email\templates\admin_dashboard.html", line 45, in top-level template code
    href="{{ url_for('admin.evidence_detail', evidence_id=e.id) }}"
    ^^^^^
  File "C:\Users\cross\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cross\AppData\Roaming\Python\Python313\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
    
  File "C:\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'admin.evidence_detail' with values ['evidence_id']. Did you mean 'admin_bp.evidence_detail' instead?
